{
 "title": "Demo Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "latency_bucket" } }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Recommendation Service (CPU%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(runtime_cpython_cpu_time{type=~\"system\"}[$__interval])*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(runtime_cpython_cpu_time{type=~\"user\"}[$__interval])*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recommendation Service (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(runtime_cpython_memory{type=~\"rss|vms\"}[$__interval])/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recommendations Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(app_recommendations_counter{recommendation_type=\"catalog\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(calls_total{status_code=\"STATUS_CODE_ERROR\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Latency (from SpanMetrics)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(latency_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(latency_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(latency_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(latency_count{service_name=\"${service}\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Opentelemetry Collector Data Flow",
 "description": "otelcol metrics dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_version",
    "label": "service_version",
    "query": {
     "query": "query_result(sum(otelcol_process_uptime{}) by (service_version))\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance",
   "type": "stat",
   "description": "Otel Collector Instance",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(otelcol_process_cpu_seconds{service_instance_id=~\".*\"}) by (service_instance_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu",
   "type": "gauge",
   "description": "otelcol_process_cpu_seconds",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(otelcol_process_cpu_seconds{}[$__rate_interval])*100) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Memory Rss\navg(otelcol_process_memory_rss{}) by (instance)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(otelcol_process_memory_rss{}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "options": {
    "content": "## Opentelemetry Collector Data Ingress/Egress\n\n`service_version:` ${service_version}\n\n`opentelemetry collector:` contrib\n\n"
   }
  },
  { "title": "Trace Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Export Ratio",
   "type": "gauge",
   "description": "(avg(sum by(job) (rate(otelcol_exporter_sent_spans{}[$__range]))) / avg(sum by(job) (rate(otelcol_receiver_accepted_spans{}[$__range])))) ",
   "gridPos": { "h": 19, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(sum by(job) (rate(otelcol_exporter_sent_spans{}[$__range]))) / avg(sum by(job) (rate(otelcol_receiver_accepted_spans{}[$__range])))) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "label_join(label_join(\n(rate(otelcol_receiver_accepted_spans{}[$__interval]))\n, \"id\", \"\", \"transport\", \"receiver\")\n, \"title\", \"\", \"transport\", \"receiver\")\n\nor\n\nlabel_replace(label_replace(\nsum by(service_name) (rate(otelcol_receiver_accepted_spans{}[$__interval]))\n, \"id\", \"processor\", \"dummynode\", \"\")\n, \"title\", \"processor\", \"dummynode\", \"\")\n\nor\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n, \"id\", \"$0\", \"processor\", \".*\")\n, \"title\", \"$0\", \"processor\", \".*\")\n\nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_spans{}[$__interval]))\n, \"id\", \"exporter\", \"dummynode\", \"\")\n, \"title\", \"exporter\", \"dummynode\", \"\")\n        \nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_spans{}[$__interval]))\n, \"id\", \"$0\", \"exporter\", \".*\")\n, \"title\", \"$0\", \"exporter\", \".*\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\nlabel_replace(label_join(\n(rate(otelcol_receiver_accepted_spans{}[$__interval]))\n\n ,\"source\",\"\",\"transport\",\"receiver\")\n,\"target\",\"processor\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\n  or\n\n  label_join(\nlabel_replace(label_replace(\n  (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n ,\"source\",\"processor\",\"\",\"\")\n,\"target\",\"$0\",\"processor\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\n  label_join(\nlabel_replace(label_replace(\n    (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n ,\"source\",\"$0\",\"processor\",\".*\")\n,\"target\",\"exporter\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\n  label_join(\nlabel_replace(label_replace(\n   (rate(otelcol_exporter_sent_spans{}[$__interval]))\n ,\"source\",\"exporter\",\"\",\"\")\n,\"target\",\"$0\",\"exporter\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "Spans Accepted by Receiver and Transport",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "Total Spans Accepted ",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Batch",
   "type": "stat",
   "description": "Total Batch Processed",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum{}[$__rate_interval]))  by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{}[$__interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "stat",
   "description": "Sent by Exporter",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{}[$__rate_interval])) by (exporter)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Refused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "Total Spans Accepted ",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "otelcol_exporter_send_failed_spans",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{}[$__rate_interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Sent by Exporter\notelcol_exporter_send_failed_spans",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{}[$__rate_interval])) by (exporter)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  { "title": "Metrics Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Export Ratio",
   "type": "gauge",
   "description": "avg(sum by(job) (rate(otelcol_exporter_sent_metric_points{}[$__range]))) versus avg(sum by(job) (rate(otelcol_receiver_accepted_metric_points{}[$__range])))",
   "gridPos": { "h": 19, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( avg(sum by(job) (rate(otelcol_exporter_sent_metric_points{}[$__range]))) /avg(sum by(job) (rate(otelcol_receiver_accepted_metric_points{}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "nodeGraph",
   "description": "Metrics Signalling Pipelines",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 26 },
   "targets": [
    {
     "expr": "\nlabel_join(label_join(\n(rate(otelcol_receiver_accepted_metric_points{}[$__interval]))\n, \"id\", \"\", \"transport\", \"receiver\")\n, \"title\", \"\", \"transport\", \"receiver\")\n\nor\n\nlabel_replace(label_replace(\nsum by(service_name) (rate(otelcol_receiver_accepted_spans{}[$__interval]))\n, \"id\", \"processor\", \"dummynode\", \"\")\n, \"title\", \"processor\", \"dummynode\", \"\")\n\n\n\nor\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n, \"id\", \"$0\", \"processor\", \".*\")\n, \"title\", \"$0\", \"processor\", \".*\")\n\n\n\n\n\nor\nlabel_replace(label_replace(\nsum (rate(otelcol_exporter_sent_metric_points{}[$__interval]))\n, \"id\", \"exporter\", \"dummynode\", \"\")\n, \"title\", \"exporter\", \"dummynode\", \"\")\n\nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_metric_points{}[$__interval]))\n, \"id\", \"$0\", \"exporter\", \".*\")\n, \"title\", \"$0\", \"exporter\", \".*\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\nlabel_replace(label_join(\n(rate(otelcol_receiver_accepted_metric_points{}[$__interval]))\n\n,\"source\",\"\",\"transport\",\"receiver\")\n,\"target\",\"processor\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\n\nor\n\nlabel_join(\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n,\"source\",\"processor\",\"\",\"\")\n,\"target\",\"$0\",\"processor\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\n\n\n\n\nor\n\n\nlabel_join(\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n,\"source\",\"$0\",\"processor\",\".*\")\n,\"target\",\"exporter\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\nlabel_join(\nlabel_replace(label_replace(\n(rate(otelcol_exporter_sent_metric_points{}[$__interval]))\n,\"source\",\"exporter\",\"\",\"\")\n,\"target\",\"$0\",\"exporter\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "otelcol_receiver_accepted_metric_points",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "otelcol_receiver_accepted_metric_points\nTotal Accepted ",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Batch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum{}[$__rate_interval]))  by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "Total Export ",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{}[$__rate_interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "stat",
   "description": "Sent by Exporter",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{}[$__rate_interval])) by (exporter) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Refused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "Total Refused \nsum(rate(otelcol_receiver_refused_metric_points{}[$__rate_interval])) ",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "gauge",
   "description": "Total Failed Export ",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points{}[$__rate_interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Sent by Exporter\notelcol_exporter_send_failed_spans",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points{}[$__rate_interval])) by (exporter)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  { "title": "Prometheus Scrape", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Exported/Scraped",
   "type": "gauge",
   "description": "otelcol prometheus exporter 9464 export rate versus prometheus scrape metrics",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(scrape_samples_scraped{job=\"otel\"}[$__range])/ count_over_time(scrape_samples_scraped{job=\"otel\"}[$__range])/(5*30)) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(rate(otelcol_exporter_sent_metric_points{exporter=\"prometheus\"}[$__rate_interval])) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Samples Scraped",
   "type": "stat",
   "description": "sum_over_time(scrape_samples_scraped[$__range])/ count_over_time(scrape_samples_scraped[$__range])",
   "gridPos": { "h": 9, "w": 5, "x": 3, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(scrape_samples_scraped[$__range])/ count_over_time(scrape_samples_scraped[$__range])/(5*30)",
     "legendFormat": "{{job}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "gauge",
   "description": "scrape_samples_scraped{job!=\"\"}\nTotal Samples Scraped",
   "gridPos": { "h": 9, "w": 3, "x": 8, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(scrape_samples_scraped[$__range])/ count_over_time(scrape_samples_scraped[$__range])/(5*30)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 9, "w": 8, "x": 11, "y": 46 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(\nsum (scrape_samples_scraped{job!=\"\"}) by (instance)\n, \"id\", \"$0\", \"instance\", \".*\")\n, \"title\", \"$0\", \"instance\", \".*\")\n,\"mainstat\",\"\",\"\",\"\")\n\nor \n\nlabel_replace(label_replace(label_replace(\nsum (scrape_samples_scraped{job!=\"\"})\n, \"id\", \"prometheus\", \"\", \"\")\n, \"title\", \"prometheus\", \"\", \"\")\n,\"mainstat\",\"\",\"\",\"\")\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\nlabel_replace(label_replace(\nsum (scrape_samples_scraped{job!=\"\"}) by (instance)\n,\"source\",\"$0\",\"instance\",\".*\")\n,\"target\",\"prometheus\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "Sent by Exporter",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 46 },
   "options": {
    "content": "\n \n## Prometheus Config\n\n`evaluation_interval:` 30s\n\n`scrape_interval:` 5s"
   }
  }
 ]
}
{
 "title": "OpenTelemetry Collector",
 "description": "Provides information about the status of the OpenTelemetry Collector",
 "tags": [ "opentelemetry" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "receiver", "label": "receiver", "query": "label_values(otelsvc_receiver)" },
   { "name": "exporter", "label": "exporter", "query": "label_values(otelsvc_exporter)" },
   { "name": "processor", "label": "processor", "query": "label_values(processor)" }
  ]
 },
 "panels": [
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Spans Accepted vs Refused /Second",
   "type": "graph",
   "description": "Rate of spans successfully accepted vs refused per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{receiver=~\"$receiver\"}[1m])) by (receiver)",
     "legendFormat": "{{receiver}} spans accepted / sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{receiver=~\"$receiver\"}[1m])) by (receiver)",
     "legendFormat": "{{ receiver }} spans refused /sec"
    }
   ]
  },
  {
   "title": "Metrics Accepted vs Refused Received/Second",
   "type": "graph",
   "description": "Rate of metrics successfully accepted vs refused per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points{receiver=~\"$receiver\"}[1m])) by (receiver)",
     "legendFormat": "{{receiver}} accepted /sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points{receiver=~\"$receiver\"}[1m])) by (receiver)",
     "legendFormat": "{{ receiver }} refused / sec"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Spans Exported vs Failed / Second",
   "type": "graph",
   "description": "Rate of spans successfully exported vs Failed per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{exporter=~\"$exporter\"}[1m])) by (exporter)",
     "legendFormat": "{{exporter}} sent / sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{exporter=~\"$exporter\"}[1m])) by (exporter)",
     "legendFormat": "{{ exporter }} failed /sec"
    }
   ]
  },
  {
   "title": "Metrics Exported vs failed /Second",
   "type": "graph",
   "description": "Rate of timeseries successfully exported per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{exporter=~\"$exporter\"}[1m])) by (exporter)",
     "legendFormat": "{{exporter}} sent /sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points{exporter=~\"$exporter\"}[1m])) by (exporter)",
     "legendFormat": "{{ exporter }} failed / sec"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Queued Retry Max Queue Length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(otelcol_processor_queued_retry_queue_length)",
     "legendFormat": "Queue Length"
    }
   ]
  },
  {
   "title": "Queued Retry Processor In-queue Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(otelcol_processor_queued_retry_queue_latency_sum/ otelcol_processor_queued_retry_queue_latency_count)",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Queued Retry Processor Send Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(otelcol_processor_queued_retry_send_latency_sum/ otelcol_processor_queued_retry_send_latency_count)",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Processor Spans Received, Dropped, Accepted, Refused/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_spans_received{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | received"
    },
    {
     "expr": "sum(rate(otelcol_processor_spans_dropped{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | dropped"
    },
    {
     "expr": "sum(rate(otelcol_processor_accepted_spans{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | accepted"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_spans{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | refused"
    }
   ]
  },
  {
   "title": "QueuedRetry Successful vs Failed Sent/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_queued_retry_success_send{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_queued_retry_fail_send{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Spans per Batch (avg from rates)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_spans_received{processor=~\"$processor\"}[1m]) / rate(otelcol_processor_batches_received{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Batches Received vs Dropped /Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batches_received{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | received"
    },
    {
     "expr": "sum(rate(otelcol_processor_trace_batches_dropped{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | trace dropped"
    }
   ]
  },
  {
   "title": "Successful Batches Sent Cumulative",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(otelcol_processor_queued_retry_success_send{processor=~\"$processor\"}) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Enqueued Spans Cumulative",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(otelcol_processor_spans_received{exporter=~\"$exporter\"}) by (exporter)",
     "legendFormat": "{{exporter}}"
    }
   ]
  }
 ]
}
{
 "title": "Spanmetrics Demo Dashboard",
 "description": "Spanmetrics way of demo application view.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "query_result(count by (service_name)(count_over_time(calls_total[$__range])))"
    }
   },
   {
    "name": "span_name",
    "query": {
     "query": "query_result(sum ({__name__=~\".*calls_total\",service_name=~\"$service\"})  by (span_name))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Level - Throughput and Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Top 3x3 - Service Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7,histogram_quantile(0.95, sum(rate(duration_milliseconds_bucket{service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (le,service_name)))",
     "legendFormat": "{{le}} - {{service_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum by (service_name) (rate(calls_total{service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean ERROR Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum(rate(calls_total{status_code=\"STATUS_CODE_ERROR\",service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (service_name))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "span_names Level - Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 7 span_names and Errors  (APM Table)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(7, sum(rate(calls_total{service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (span_name,service_name)) "
    },
    {
     "expr": "topk(7, sum(rate(calls_total{status_code=\"STATUS_CODE_ERROR\",service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (span_name,service_name))"
    }
   ]
  },
  {
   "title": "span_name Level - Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 3x3 - span_name Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7,histogram_quantile(0.95, sum(rate(duration_milliseconds_bucket{service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (le,span_name)))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Highest Endpoint Latencies  Mean Over Range ",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7, sum by (span_name,service_name)(increase(duration_milliseconds_sum{service_name=~\"${service}\", span_name=~\"$span_name\"}[5m]) / increase(duration_milliseconds_count{service_name=~\"${service}\",span_name=~\"$span_name\"}[5m\n])))",
     "legendFormat": "{{span_name}} [{{service_name}}]"
    }
   ]
  },
  {
   "title": "Top 7 Latencies Over Range ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(7,sum by (span_name,service_name)(increase(duration_milliseconds_sum{service_name=~\"$service\", span_name=~\"$span_name\"}[$__rate_interval]) / increase(duration_milliseconds_count{service_name=~\"$service\", span_name=~\"$span_name\"}[$__rate_interval])))",
     "legendFormat": "[{{service_name}}]  {{span_name}}"
    }
   ]
  }
 ]
}