{{- if and .Values.tenx.enabled .Values.tenx.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-tenx-api-key
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.tenx.apiKey | b64enc | quote }}
{{- end }}
{{- if and .Values.tenx.enabled .Values.tenx.gitToken }}
{{- if .Values.tenx.apiKey }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-tenx-git-token
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.tenx.gitToken | b64enc | quote }}
{{- end }}
