---
apiVersion: v2
name: opentelemetry-otap-dataflow
version: 0.1.0
description: OpenTelemetry OTAP dataflow (df-engine) Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/otel-arrow/tree/main/rust/otap-dataflow
  - https://github.com/open-telemetry/opentelemetry-helm-charts
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
maintainers:
  - name: dmitryax
  - name: jaronoff97
  - name: TylerHelmuth
appVersion: 0.50.0
