{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "helper.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Expand the name of the chart.
*/}}
{{- define "helper.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "helper.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Helper used to define a namspace.
- Returns namespace from a release
- If namespaceOverride value is filled in it will replace the namespace
*/}}
{{- define "helper.namespace" -}}
  {{- default .Release.Namespace .Values.namespaceOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Selector Labels
*/}}
{{- define "helper.selectorLabels" -}}
app.kubernetes.io/name: {{ include "helper.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Common labels shared by all Kubernetes objects in this chart.
*/}}
{{- define "helper.commonLabels" -}}
helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/part-of: opentelemetry-auto-instrumentation
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{ include "helper.selectorLabels" . }}
{{- end }}

{{/*
Create the name of the manager service account to use
*/}}
{{- define "helper.managerServiceAccountName" -}}
{{- default (printf "%s-manager" ( include "helper.fullname" .) | trunc 63 | trimSuffix "-") .Values.manager.serviceAccount.name -}}
{{- end -}}

{{/*
Create the name of the manager cluster role to use
*/}}
{{- define "helper.managerClusterRoleName" -}}
{{- printf "%s-manager-clusterRole" ( include "helper.fullname" . ) | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Get ConfigMap name if existingName is defined, otherwise use default name for generated config.
*/}}
{{- define "helper.managerConfigMapName" -}}
  {{- if .Values.configMap.existingName -}}
    {{- tpl (.Values.configMap.existingName | toYaml) . }}
  {{- else }}
    {{- printf "%s-manager-configmap" ( include "helper.fullname" . ) | trunc 63 | trimSuffix "-" -}}
  {{- end -}}
{{- end }}

{{/*
Create the name of the manager cluster role binding to use
*/}}
{{- define "helper.managerClusterRoleBindingName" -}}
{{- printf "%s-manager-clusterRoleBinding" ( include "helper.fullname" . ) | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create the manager docker image name.
*/}}
{{- define "helper.dockerImageName" -}}
{{- printf "%s:%s" .Values.manager.image.repository (.Values.manager.image.tag | default .Chart.AppVersion) -}}
{{- end -}}

{{/*
Create ConfigMap checksum annotation
*/}}
{{- define "helper.configTemplateChecksumAnnotation" -}}
checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- end -}}

{{/*
Return certificate and CA for Webhooks.
It handles variants when a cert has to be generated by Helm,
a cert is loaded from an existing secret or is provided via `.Values`
*/}}
{{- define "helper.WebhookCert" -}}
{{- $caCertEnc := "" }}
{{- $certCrtEnc := "" }}
{{- $certKeyEnc := "" }}
{{- if .Values.cert.create }}
{{- $prevSecret := (lookup "v1" "Secret" (include "helper.namespace" .) (default (printf "%s-manager-service-cert" (include "helper.fullname" .)) .Values.cert.secretName )) }}
{{- if and (not .Values.cert.recreate) $prevSecret }}
{{- $certCrtEnc = index $prevSecret "data" "tls.crt" }}
{{- $certKeyEnc = index $prevSecret "data" "tls.key" }}
{{- $caCertEnc = index $prevSecret "data" "ca.crt" }}
{{- if not $caCertEnc }}
{{- $prevHook := (lookup "admissionregistration.k8s.io/v1" "MutatingWebhookConfiguration" (include "helper.namespace" .) (print (include "helper.fullname" . ) "-mutation")) }}
{{- if not (eq (toString $prevHook) "<nil>") }}
{{- $caCertEnc = (first $prevHook.webhooks).clientConfig.caBundle }}
{{- end }}
{{- end }}
{{- else }}
{{- $altNames := list ( printf "%s-webhook.%s" (include "helper.fullname" .) (include "helper.namespace" .) ) ( printf "%s-webhook.%s.svc" (include "helper.fullname" .) (include "helper.namespace" .) ) -}}
{{- $tmpperioddays := int .Values.cert.certPeriodDays | default 365 }}
{{- $ca := genCA "opentelemetry-operator-operator-ca" $tmpperioddays }}
{{- $cert := genSignedCert (include "helper.fullname" .) nil $altNames $tmpperioddays $ca }}
{{- $certCrtEnc = b64enc $cert.Cert }}
{{- $certKeyEnc = b64enc $cert.Key }}
{{- $caCertEnc = b64enc $ca.Cert }}
{{- end }}
{{- else }}
{{- $certCrtEnc = .Files.Get .Values.cert.certFile | b64enc }}
{{- $certKeyEnc = .Files.Get .Values.cert.keyFile | b64enc }}
{{- $caCertEnc = .Files.Get .Values.cert.caFile | b64enc }}
{{- end }}
{{- $result := dict "crt" $certCrtEnc "key" $certKeyEnc "ca" $caCertEnc }}
{{- $result | toYaml }}
{{- end }}

{{/*
Create an ordered name of the MutatingWebhookConfiguration
*/}}
{{- define "helper.MutatingWebhookName" -}}
{{- printf "%s-%s" (.Values.webhook.namePrefix | toString) (include "helper.fullname" .) | trimPrefix "-" }}
{{- end }}
