{{- if .Values.manager.serviceAccount.create }}
apiVersion: v1
{{- if .Values.manager.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.manager.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{ template "helper.managerServiceAccountName" . }}
  namespace: {{ template "helper.namespace" . }}
  labels:
    {{- include "helper.commonLabels" . | nindent 4 }}
  {{- if .Values.manager.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.manager.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
