rewriteDeprecatedComponentNames: false

collectors:
  component-aliases-disabled:
    enabled: true
    suffix: component-aliases-disabled
    mode: daemonset
    presets:
      logsCollection:
        enabled: true
      hostMetrics:
        enabled: true
      kubernetesAttributes:
        enabled: true
      kubeletMetrics:
        enabled: true
      kubernetesEvents:
        enabled: true
      resourceDetection:
        eks:
          enabled: true
    config:
      receivers:
        hostmetrics:
          collection_interval: 1m
