collectors:
  daemon:
    scrape_configs_file: ""
    presets:
      logsCollection:
        enabled: false
      kubeletMetrics:
        enabled: false
      hostMetrics:
        enabled: false
      kubernetesAttributes:
        enabled: false
      kubernetesEvents:
        enabled: false
      clusterMetrics:
        enabled: false
      kubernetesObjects:
        enabled: true
    config:
      exporters:
        debug: {}
      service:
        pipelines:
          logs:
            receivers: []
            exporters:
              - debug
