{
 "title": "Kubernetes / Persistent Volumes / All Nodes - OTEL",
 "tags": [ "otel" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(k8s_volume_capacity_bytes{}, k8s_cluster_name)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(k8s_volume_capacity_bytes{k8s_cluster_name=\"$cluster\"}, k8s_namespace_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Space Usage by Claim",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  max by (k8s_namespace_name, k8s_persistentvolumeclaim_name) (k8s_volume_capacity_bytes{k8s_namespace_name=~\"$namespace\"})\n  -\n  max by (k8s_namespace_name, k8s_persistentvolumeclaim_name) (k8s_volume_available_bytes{k8s_namespace_name=~\"$namespace\"})\n)\n",
     "legendFormat": "{{k8s_namespace_name}}/{{k8s_persistentvolumeclaim_name}} Used Space"
    },
    {
     "expr": "max by (k8s_namespace_name, k8s_persistentvolumeclaim_name) (k8s_volume_available_bytes{k8s_namespace_name=~\"$namespace\"})\n",
     "legendFormat": "{{k8s_namespace_name}}/{{k8s_persistentvolumeclaim_name}} Free Space"
    }
   ]
  },
  {
   "title": "Highest Volume Space Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n(\n  max by (k8s_namespace_name, k8s_persistentvolumeclaim_name) (k8s_volume_capacity_bytes{k8s_namespace_name=~\"$namespace\"})\n  -\n  max by (k8s_namespace_name, k8s_persistentvolumeclaim_name) (k8s_volume_available_bytes{k8s_namespace_name=~\"$namespace\"})\n)\n/\nmax by (k8s_namespace_name, k8s_persistentvolumeclaim_name) (k8s_volume_capacity_bytes{k8s_namespace_name=~\"$namespace\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Volume Inodes Usage by Claim",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (k8s_namespace_name, k8s_persistentvolumeclaim_name) (k8s_volume_inodes_used_ratio{k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "{{k8s_namespace_name}}/{{k8s_persistentvolumeclaim_name}} Used inodes"
    },
    {
     "expr": "(\n  max by (k8s_namespace_name, k8s_persistentvolumeclaim_name) (k8s_volume_inodes_ratio{k8s_namespace_name=~\"$namespace\"})\n  -\n  max by (k8s_namespace_name, k8s_persistentvolumeclaim_name) (k8s_volume_inodes_used_ratio{k8s_namespace_name=~\"$namespace\"})\n)\n",
     "legendFormat": "{{k8s_namespace_name}}/{{k8s_persistentvolumeclaim_name}} Free inodes"
    }
   ]
  },
  {
   "title": "Highest Volume Inodes Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\nmax by (k8s_namespace_name, k8s_persistentvolumeclaim_name) (k8s_volume_inodes_used_ratio{k8s_namespace_name=~\"$namespace\"})\n/\nmax by (k8s_namespace_name, k8s_persistentvolumeclaim_name) (k8s_volume_inodes_ratio{k8s_namespace_name=~\"$namespace\"})\n* 100\n)\n"
    }
   ]
  }
 ]
}