{
 "title": "Kubernetes / Networking / Namespace (Workload) - OTEL",
 "tags": [ "otel" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(k8s_pod_network_io_bytes_total, k8s_cluster_name)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\"}, k8s_namespace_name)"
   },
   {
    "name": "type",
    "label": "workload_type",
    "query": "deployment,statefulset,daemonset,job,cronjob"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Rate of Bits Received",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (workload, workload_type) (label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_deployment_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_statefulset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_daemonset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_job_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_cronjob_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Current Rate of Bits Transmitted",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (workload, workload_type) (label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_deployment_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_statefulset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_daemonset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_job_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_cronjob_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sort_desc(sum by (workload, workload_type) (label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_deployment_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_statefulset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_daemonset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_job_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_cronjob_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))"
    },
    {
     "expr": "sort_desc(sum by (workload, workload_type) (label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_deployment_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_statefulset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_daemonset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_job_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_cronjob_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))"
    },
    {
     "expr": "sort_desc(avg by (workload, workload_type) (label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_deployment_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_statefulset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_daemonset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_job_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_cronjob_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))"
    },
    {
     "expr": "sort_desc(avg by (workload, workload_type) (label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_deployment_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_statefulset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_daemonset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_job_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_cronjob_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))"
    },
    {
     "expr": "sort_desc(sum by (workload, workload_type) (label_replace(label_replace(rate(k8s_pod_network_packets_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_deployment_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_packets_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_statefulset_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_packets_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_daemonset_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_packets_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_job_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_packets_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_cronjob_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))"
    },
    {
     "expr": "sort_desc(sum by (workload, workload_type) (label_replace(label_replace(rate(k8s_pod_network_packets_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_deployment_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_packets_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_statefulset_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_packets_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_daemonset_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_packets_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_job_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_packets_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_cronjob_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))"
    },
    {
     "expr": "sort_desc(sum by (workload, workload_type) (label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_deployment_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_statefulset_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_daemonset_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_job_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_cronjob_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))"
    },
    {
     "expr": "sort_desc(sum by (workload, workload_type) (label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_deployment_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_statefulset_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_daemonset_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_job_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_cronjob_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (workload, workload_type) (label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_deployment_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_statefulset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_daemonset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_job_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_cronjob_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (workload, workload_type) (label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_deployment_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_statefulset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_daemonset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_job_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_cronjob_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Workload: Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sort_desc(avg by (workload, workload_type) (label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_deployment_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_statefulset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_daemonset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_job_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_cronjob_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Workload: Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sort_desc(avg by (workload, workload_type) (label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_deployment_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_statefulset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_daemonset_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_job_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace((8 * rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_cronjob_name!=\"\"}[$__rate_interval])), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (workload, workload_type) (label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_deployment_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_statefulset_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_daemonset_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_job_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"receive\",k8s_cronjob_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (workload, workload_type) (label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_deployment_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_deployment_name\", \"(.*)\"), \"workload_type\", \"deployment\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_statefulset_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_statefulset_name\", \"(.*)\"), \"workload_type\", \"statefulset\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_daemonset_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_daemonset_name\", \"(.*)\"), \"workload_type\", \"daemonset\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_job_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_job_name\", \"(.*)\"), \"workload_type\", \"job\", \"__name__\", \".*\") or label_replace(label_replace(rate(k8s_pod_network_errors_total{k8s_cluster_name=\"$cluster\",k8s_namespace_name=\"$namespace\",direction=\"transmit\",k8s_cronjob_name!=\"\"}[$__rate_interval]), \"workload\", \"$1\", \"k8s_cronjob_name\", \"(.*)\"), \"workload_type\", \"cronjob\", \"__name__\", \".*\")))",
     "legendFormat": "{{workload}}"
    }
   ]
  }
 ]
}