{
 "title": "Kubernetes / Compute Resources / Node (Pods) - OTEL",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(k8s_pod_cpu_time_seconds_total,k8s_node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(k8s_node_cpu_capacity{k8s_node_name=~\"$node\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(k8s_node_allocatable_cpu{k8s_node_name=~\"$node\"})",
     "legendFormat": "max allocatable"
    },
    {
     "expr": "sum by(k8s_pod_name) (rate(k8s_pod_cpu_time_seconds_total{k8s_node_name=~\"$node\"}[5m]))",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(k8s_pod_name) (rate(k8s_pod_cpu_time_seconds_total{k8s_node_name=~\"$node\"}[5m]))",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "sum by(k8s_pod_name) (k8s_container_cpu_request{k8s_node_name=~\"$node\"})",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "sum by(k8s_pod_name) (rate(k8s_pod_cpu_time_seconds_total{k8s_node_name=~\"$node\"}[5m])) / (sum by(k8s_pod_name) (k8s_container_cpu_request{k8s_node_name=~\"$node\"}))",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "sum by(k8s_pod_name) (k8s_container_cpu_limit{k8s_node_name=~\"$node\"})",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "sum by(k8s_pod_name) (rate(k8s_pod_cpu_time_seconds_total{k8s_node_name=~\"$node\"}[5m])) / (sum by(k8s_pod_name) (k8s_container_cpu_limit{k8s_node_name=~\"$node\"}))",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (total)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(k8s_node_memory_capacity_bytes{k8s_node_name=~\"$node\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(k8s_node_allocatable_memory_bytes{k8s_node_name=~\"$node\"})",
     "legendFormat": "max allocatable"
    },
    {
     "expr": "sum by(k8s_pod_name) (k8s_pod_memory_usage_bytes{k8s_node_name=~\"$node\"})",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (working set)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(k8s_node_memory_capacity_bytes{k8s_node_name=~\"$node\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(k8s_node_allocatable_memory_bytes{k8s_node_name=~\"$node\"})",
     "legendFormat": "max allocatable"
    },
    {
     "expr": "sum by(k8s_pod_name) (k8s_pod_memory_working_set_bytes{k8s_node_name=~\"$node\"})",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(k8s_pod_name) (k8s_pod_memory_usage_bytes{k8s_node_name=~\"$node\"})",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "sum by(k8s_pod_name) (k8s_container_memory_request_bytes{k8s_node_name=~\"$node\"})",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "sum by(k8s_pod_name) (k8s_pod_memory_usage_bytes{k8s_node_name=~\"$node\"}) / (sum by(k8s_pod_name) (k8s_container_memory_request_bytes{k8s_node_name=~\"$node\"}))",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "sum by(k8s_pod_name) (k8s_container_memory_limit_bytes{k8s_node_name=~\"$node\"})",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "sum by(k8s_pod_name) (k8s_pod_memory_usage_bytes{k8s_node_name=~\"$node\"}) / (sum by(k8s_pod_name) (k8s_container_memory_limit_bytes{k8s_node_name=~\"$node\"}))",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "sum by(k8s_pod_name) (k8s_pod_memory_working_set_bytes{k8s_node_name=~\"$node\"})",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "sum by(k8s_pod_name) (k8s_pod_memory_rss_bytes{k8s_node_name=~\"$node\"})",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "sum by(k8s_pod_name) (k8s_pod_memory_usage_bytes{k8s_node_name=~\"$node\"}) - (sum by(k8s_pod_name) (k8s_pod_memory_working_set_bytes{k8s_node_name=~\"$node\"}))",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  }
 ]
}