{
 "title": "Node Exporter / USE Method / Node - OTEL",
 "tags": [ "node-exporter-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(k8s_node_cpu_time_seconds_total, k8s_cluster_name)"
   },
   {
    "name": "instance",
    "query": "label_values(k8s_node_cpu_time_seconds_total{k8s_cluster_name=~\"$cluster\"}, k8s_node_name)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (k8s_node_name) (\r\n  rate(k8s_node_cpu_time_seconds_total{k8s_node_name=~\"$instance\"}[5m])\r\n)",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1 per CPU)",
   "type": "timeseries",
   "description": "Assumption: requested/allocatable CPU as saturation proxy.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(k8s_container_cpu_request{k8s_node_name=~\"$instance\"}) / (avg(k8s_node_allocatable_cpu{k8s_node_name=~\"$instance\"}))",
     "legendFormat": "Saturation"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(k8s_node_memory_usage_bytes{k8s_node_name=~\"$instance\"}) / (avg(k8s_node_memory_usage_bytes{k8s_node_name=~\"$instance\"}) + (avg(k8s_node_memory_available_bytes{k8s_cluster_name=~\"$cluster\", k8s_node_name=~\"$instance\"})))",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Memory Saturation (Major Page Faults)",
   "type": "timeseries",
   "description": "Assumption: requested/allocatable memory as saturation proxy.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rds" } },
   "targets": [
    {
     "expr": "sum(k8s_container_memory_request_bytes{k8s_node_name=~\"$instance\"}) / (avg(k8s_node_allocatable_memory_bytes{k8s_node_name=~\"$instance\"}))",
     "legendFormat": "Major page Faults"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Network Utilisation (Bytes Receive/Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(system_network_io_bytes_total{k8s_cluster_name=~\"$cluster\",k8s_node_name=~\"$instance\",direction=\"receive\"}[5m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(system_network_io_bytes_total{k8s_cluster_name=~\"$cluster\",k8s_node_name=~\"$instance\",direction=\"transmit\"}[5m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Network Saturation (Drops Receive/Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(system_network_dropped_total{k8s_node_name=~\"$instance\", direction=\"receive\"}[5m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(system_network_dropped_total{k8s_node_name=~\"$instance\", direction=\"transmit\"}[5m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk IO Utilisation",
   "type": "timeseries",
   "description": "Assumption: filesystem usage replaces disk IO utilisation.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  sum(k8s_node_filesystem_available_bytes{k8s_cluster_name=~\"$cluster\",k8s_node_name=~\"$instance\"})\n  /\n  sum(k8s_node_filesystem_capacity_bytes{k8s_cluster_name=~\"$cluster\",k8s_node_name=~\"$instance\"})\n)",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "timeseries",
   "description": "Assumption: ephemeral storage requests/capacity as IO saturation proxy.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(k8s_container_ephemeralstorage_request_bytes{k8s_node_name=~\"$instance\"}) / avg(k8s_node_filesystem_capacity_bytes{k8s_node_name=~\"$instance\"})",
     "legendFormat": "Saturation"
    }
   ]
  },
  { "title": "Disk Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Disk Space Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(1 -\n  (\n    k8s_node_filesystem_available_bytes{k8s_node_name=~\"$instance\"}\n    /\n    k8s_node_filesystem_capacity_bytes{k8s_node_name=~\"$instance\"}\n  )\n)",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  }
 ]
}