mode: deployment

image:
  repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"

command:
  name: "otelcol-k8s"

config:
  receivers:
    otlp: {}
  exporters:
    otlp_grpc:
      endpoint: "localhost:4317"
      tls:
        insecure: true
    otlp_grpc/backend:
      endpoint: "localhost:4317"
      tls:
        insecure: true
    otlp_http:
      endpoint: "http://localhost:4318"
    otlp_http/backend:
      endpoint: "http://localhost:4318"
  service:
    pipelines:
      traces:
        receivers:
          - otlp
        exporters:
          - otlp_grpc
          - otlp_grpc/backend
          - otlp_http
          - otlp_http/backend

resources:
  limits:
    cpu: 100m
    memory: 200M
