mode: daemonset

image:
  repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-ebpf-profiler"

command:
  name: "otelcol-ebpf-profiler"
  extraArgs: ["--feature-gates=+service.profilesSupport"]

presets:
  profiling:
    enabled: true

resources:
  limits:
    cpu: 100m
    memory: 200M
