apiVersion: v1
kind: Service
metadata:
  name: {{ include "otap-dataflow.fullname" . }}
  namespace: {{ include "otap-dataflow.namespace" . }}
  labels:
    {{- include "helper.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: service
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $name, $port := .Values.ports }}
    {{- if $port.enabled }}
    - name: {{ $name }}
      port: {{ $port.servicePort }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol | default "TCP" }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "otap-dataflow.selectorLabels" . | nindent 4 }}
