{
 "title": "Demo Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "traces_span_metrics_duration_milliseconds_bucket"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows RED metrics for the selected service, as generated by the spanmetrics connector in the OpenTelemetry Collector.\nIf the selected service emits logs, the logs will also be displayed.\nCustom metrics generated by some services are also displayed.\n<br>\nChart panels may require 5 minutes after the Demo is started before rendering data."
   }
  },
  { "title": "Spanmetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Latency for ${service}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile999"
    }
   ]
  },
  {
   "title": "Error Rate for ${service} by span name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": " sum by (span_name) (rate(traces_span_metrics_calls_total{status_code=\"STATUS_CODE_ERROR\", service_name=\"${service}\"}[$__rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  {
   "title": "Requests Rate for ${service} by span name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (span_name) (rate(traces_span_metrics_duration_milliseconds_count{service_name=\"${service}\"}[$__rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  { "title": "Application Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "${service} Log entries by Severity",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where resource.service.name=\"${service}\"\n| stats count() by severity.text",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "${service} Logs (100 recent entries)",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where resource.service.name=\"${service}\"| sort - observedTimestamp | head 100",
     "timeField": "observedTimestamp"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Python services (CPU%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_runtime_cpython_cpu_time_seconds_total{type=~\"system\"}[$__rate_interval])*100",
     "legendFormat": "{{job}} ({{type}})"
    },
    {
     "expr": "rate(process_runtime_cpython_cpu_time_seconds_total{type=~\"user\"}[$__rate_interval])*100",
     "legendFormat": "{{job}} ({{type}})"
    }
   ]
  },
  {
   "title": "Python services (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_cpython_memory_bytes{type=\"rss\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Recommendations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rate(app_recommendations_counter_total{recommendation_type=\"catalog\"}[$__rate_interval])",
     "legendFormat": "recommendations"
    }
   ]
  },
  {
   "title": "Quote Service batch span processor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "rate(otel_trace_span_processor_spans{job=\"quote\"}[2m])*120",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}