global:
  domain: "us1.coralogix.com"
  clusterName: "test-cluster"
  defaultApplicationName: "test-app"

collectorCRD:
  generate: true

presets:
  logsCollection:
    enabled: true
    storeCheckpoints: true

securityContext:
  runAsUser: 0
  runAsGroup: 0
