collectors:
  daemon:
    presets:
      kubernetesAttributes:
        enabled: true
      logsCollection:
        enabled: false
      kubeletMetrics:
        enabled: false
      hostMetrics:
        enabled: false
      kubernetesEvents:
        enabled: false
      clusterMetrics:
        enabled: false

