{{- $configMeta := include "obi.configMeta" . | fromYaml }}
{{- $metricsPort := .Values.service.targetPort | default $configMeta.prometheusPort }}
{{- $internalMetricsPort := .Values.service.internalMetrics.targetPort | default $configMeta.internalMetricsPort }}
{{- if and .Values.service.enabled .Values.serviceMonitor.enabled (or $metricsPort $internalMetricsPort) }}
{{- $root := . }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "obi.fullname" . }}
  namespace: {{ include "obi.namespace" .}}
  labels:
    {{- include "obi.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- tpl (toYaml . | nindent 4) $root }}
  {{- end }}
spec:
  endpoints:
    {{- if $metricsPort }}
    {{- $metricsEndpoint := mergeOverwrite (dict "port" .Values.service.portName "path" ($configMeta.prometheusPath | default "/metrics") "scheme" "http") (deepCopy .Values.serviceMonitor.metrics.endpoint) }}
    - {{- toYaml $metricsEndpoint | nindent 6 }}
    {{- end }}
    {{- if and $internalMetricsPort (ne $metricsPort $internalMetricsPort) }}
    {{- $internalEndpoint := mergeOverwrite (dict "port" .Values.service.internalMetrics.portName "path" ($configMeta.internalMetricsPath | default "/internal/metrics") "scheme" "http") (deepCopy .Values.serviceMonitor.internalMetrics.endpoint) }}
    - {{- toYaml $internalEndpoint | nindent 6 }}
    {{- end }}
  jobLabel: {{ .Values.serviceMonitor.jobLabel | default (include "obi.fullname" .) }}
  selector:
    matchLabels:
      {{- include "obi.labels" . | nindent 6 }}
      {{- with .Values.service.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
